services:
  postgres:
    image: postgres:15
    container_name: postgres_spring
    restart: unless-stopped
    environment:
      POSTGRES_DB: app_db
      POSTGRES_USER: app_user
      POSTGRES_PASSWORD: secretpass
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - spring-net

volumes:
  postgres_data:

networks:
  spring-net:
    driver: bridge
